#testcard = Card('Clubs', 6)
#testcard.show()
#deck = warClasses.Deck()
#deck.shuffle()
#deck.deal()
#deck.show()
#player1 = warClasses.Player(player1)
#player1.playerHand()
#player1.show()
#print('\n')
#player2 = warClasses.Player(player2)
#player2.playerHand()
#player2.show()